image: docker:latest
services:
  - name: docker:dind
    command: ["--insecure-registry=registry.gitlab.winllc-dev.com"]

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - publish

publish-artificat:
  image: gradle:jdk14
  stage: publish
  script:
    - gradle clean publish