image: docker:latest
services:
  - name: docker:dind
    command: ["--insecure-registry=registry.gitlab.winllc-dev.com"]

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - publish

build:
  image: gradle:7.1-jdk11
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - build/libs/*.jar

publish-artificat:
  image: gradle:7.1-jdk11
  stage: publish
  script:
    - gradle publish