image: docker:latest
services:
  - name: docker:dind
    command: ["--insecure-registry=registry.gitlab.winllc-dev.com"]

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - build
  - package

test:
  image: openjdk:14
  stage: test
  script:
    - ./gradlew test

build:
  image: openjdk:14
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar

publish-artifact:
  image: openjdk:14
  stage: publish
  script:
    - ./gradlew publish