image: docker:latest
services:
  - docker:20:10:16-dind

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - build
  - publish

test:
  image: openjdk:17
  stage: test
  script:
    - ./gradlew test

build:
  image: openjdk:17
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar

publish:
  image: openjdk:17
  stage: publish
  script:
    - ./gradlew publish