package com.winllc.acme.common.constants;

public enum AuditRecordType {
    CERTIFICATE_ISSUED,
    CERTIFICATE_REVOKED,
    SERVER_ENTRY_ADDED,
    SERVER_ENTRY_UPDATED,
    SERVER_ENTRY_REMOVED,
    ACCOUNT_ADDED,
    ACCOUNT_POCS_UPDATED,
    ACCOUNT_REMOVED,
    DOMAIN_LINK_TO_ACCOUNT_REQUEST_CREATED,
    DOMAIN_LINK_TO_ACCOUNT_REQUEST_APPROVED,
    DOMAIN_LINK_TO_ACCOUNT_REQUEST_REJECTED,
    OPENID_ENABLED,
    OPENID_DISABLED
}
