/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.winllc.acme.common.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * AuditMetricResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-12T15:21:01.254Z[GMT]")
public class AuditMetricResponse {
  @SerializedName("dateFormat")
  private String dateFormat = null;

  @SerializedName("auditMetrics")
  private List<DailyAuditMetric> auditMetrics = null;

  public AuditMetricResponse dateFormat(String dateFormat) {
    this.dateFormat = dateFormat;
    return this;
  }

   /**
   * Get dateFormat
   * @return dateFormat
  **/
  @Schema(description = "")
  public String getDateFormat() {
    return dateFormat;
  }

  public void setDateFormat(String dateFormat) {
    this.dateFormat = dateFormat;
  }

  public AuditMetricResponse auditMetrics(List<DailyAuditMetric> auditMetrics) {
    this.auditMetrics = auditMetrics;
    return this;
  }

  public AuditMetricResponse addAuditMetricsItem(DailyAuditMetric auditMetricsItem) {
    if (this.auditMetrics == null) {
      this.auditMetrics = new ArrayList<DailyAuditMetric>();
    }
    this.auditMetrics.add(auditMetricsItem);
    return this;
  }

   /**
   * Get auditMetrics
   * @return auditMetrics
  **/
  @Schema(description = "")
  public List<DailyAuditMetric> getAuditMetrics() {
    return auditMetrics;
  }

  public void setAuditMetrics(List<DailyAuditMetric> auditMetrics) {
    this.auditMetrics = auditMetrics;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditMetricResponse auditMetricResponse = (AuditMetricResponse) o;
    return Objects.equals(this.dateFormat, auditMetricResponse.dateFormat) &&
        Objects.equals(this.auditMetrics, auditMetricResponse.auditMetrics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateFormat, auditMetrics);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditMetricResponse {\n");
    
    sb.append("    dateFormat: ").append(toIndentedString(dateFormat)).append("\n");
    sb.append("    auditMetrics: ").append(toIndentedString(auditMetrics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
