/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.winllc.acme.common.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Body1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-12T15:21:01.254Z[GMT]")
public class Body1 {
  @SerializedName("form")
  private CertificateRequestForm form = null;

  @SerializedName("raUser")
  private UserDetails raUser = null;

  public Body1 form(CertificateRequestForm form) {
    this.form = form;
    return this;
  }

   /**
   * Get form
   * @return form
  **/
  @Schema(description = "")
  public CertificateRequestForm getForm() {
    return form;
  }

  public void setForm(CertificateRequestForm form) {
    this.form = form;
  }

  public Body1 raUser(UserDetails raUser) {
    this.raUser = raUser;
    return this;
  }

   /**
   * Get raUser
   * @return raUser
  **/
  @Schema(description = "")
  public UserDetails getRaUser() {
    return raUser;
  }

  public void setRaUser(UserDetails raUser) {
    this.raUser = raUser;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body1 body1 = (Body1) o;
    return Objects.equals(this.form, body1.form) &&
        Objects.equals(this.raUser, body1.raUser);
  }

  @Override
  public int hashCode() {
    return Objects.hash(form, raUser);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body1 {\n");
    
    sb.append("    form: ").append(toIndentedString(form)).append("\n");
    sb.append("    raUser: ").append(toIndentedString(raUser)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
