/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.winllc.acme.common.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * CertIssuanceValidationRule
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-12T15:21:01.254Z[GMT]")
public class CertIssuanceValidationRule {
  @SerializedName("identifierType")
  private String identifierType = null;

  @SerializedName("baseDomainName")
  private String baseDomainName = null;

  @SerializedName("requireDnsChallenge")
  private Boolean requireDnsChallenge = null;

  @SerializedName("requireHttpChallenge")
  private Boolean requireHttpChallenge = null;

  @SerializedName("allowIssuance")
  private Boolean allowIssuance = null;

  @SerializedName("allowHostnameIssuance")
  private Boolean allowHostnameIssuance = null;

  public CertIssuanceValidationRule identifierType(String identifierType) {
    this.identifierType = identifierType;
    return this;
  }

   /**
   * Get identifierType
   * @return identifierType
  **/
  @Schema(description = "")
  public String getIdentifierType() {
    return identifierType;
  }

  public void setIdentifierType(String identifierType) {
    this.identifierType = identifierType;
  }

  public CertIssuanceValidationRule baseDomainName(String baseDomainName) {
    this.baseDomainName = baseDomainName;
    return this;
  }

   /**
   * Get baseDomainName
   * @return baseDomainName
  **/
  @Schema(description = "")
  public String getBaseDomainName() {
    return baseDomainName;
  }

  public void setBaseDomainName(String baseDomainName) {
    this.baseDomainName = baseDomainName;
  }

  public CertIssuanceValidationRule requireDnsChallenge(Boolean requireDnsChallenge) {
    this.requireDnsChallenge = requireDnsChallenge;
    return this;
  }

   /**
   * Get requireDnsChallenge
   * @return requireDnsChallenge
  **/
  @Schema(description = "")
  public Boolean isRequireDnsChallenge() {
    return requireDnsChallenge;
  }

  public void setRequireDnsChallenge(Boolean requireDnsChallenge) {
    this.requireDnsChallenge = requireDnsChallenge;
  }

  public CertIssuanceValidationRule requireHttpChallenge(Boolean requireHttpChallenge) {
    this.requireHttpChallenge = requireHttpChallenge;
    return this;
  }

   /**
   * Get requireHttpChallenge
   * @return requireHttpChallenge
  **/
  @Schema(description = "")
  public Boolean isRequireHttpChallenge() {
    return requireHttpChallenge;
  }

  public void setRequireHttpChallenge(Boolean requireHttpChallenge) {
    this.requireHttpChallenge = requireHttpChallenge;
  }

  public CertIssuanceValidationRule allowIssuance(Boolean allowIssuance) {
    this.allowIssuance = allowIssuance;
    return this;
  }

   /**
   * Get allowIssuance
   * @return allowIssuance
  **/
  @Schema(description = "")
  public Boolean isAllowIssuance() {
    return allowIssuance;
  }

  public void setAllowIssuance(Boolean allowIssuance) {
    this.allowIssuance = allowIssuance;
  }

  public CertIssuanceValidationRule allowHostnameIssuance(Boolean allowHostnameIssuance) {
    this.allowHostnameIssuance = allowHostnameIssuance;
    return this;
  }

   /**
   * Get allowHostnameIssuance
   * @return allowHostnameIssuance
  **/
  @Schema(description = "")
  public Boolean isAllowHostnameIssuance() {
    return allowHostnameIssuance;
  }

  public void setAllowHostnameIssuance(Boolean allowHostnameIssuance) {
    this.allowHostnameIssuance = allowHostnameIssuance;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertIssuanceValidationRule certIssuanceValidationRule = (CertIssuanceValidationRule) o;
    return Objects.equals(this.identifierType, certIssuanceValidationRule.identifierType) &&
        Objects.equals(this.baseDomainName, certIssuanceValidationRule.baseDomainName) &&
        Objects.equals(this.requireDnsChallenge, certIssuanceValidationRule.requireDnsChallenge) &&
        Objects.equals(this.requireHttpChallenge, certIssuanceValidationRule.requireHttpChallenge) &&
        Objects.equals(this.allowIssuance, certIssuanceValidationRule.allowIssuance) &&
        Objects.equals(this.allowHostnameIssuance, certIssuanceValidationRule.allowHostnameIssuance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifierType, baseDomainName, requireDnsChallenge, requireHttpChallenge, allowIssuance, allowHostnameIssuance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertIssuanceValidationRule {\n");
    
    sb.append("    identifierType: ").append(toIndentedString(identifierType)).append("\n");
    sb.append("    baseDomainName: ").append(toIndentedString(baseDomainName)).append("\n");
    sb.append("    requireDnsChallenge: ").append(toIndentedString(requireDnsChallenge)).append("\n");
    sb.append("    requireHttpChallenge: ").append(toIndentedString(requireHttpChallenge)).append("\n");
    sb.append("    allowIssuance: ").append(toIndentedString(allowIssuance)).append("\n");
    sb.append("    allowHostnameIssuance: ").append(toIndentedString(allowHostnameIssuance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
