/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.winllc.acme.common.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * CertificateAuthoritySettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-12T15:21:01.254Z[GMT]")
public class CertificateAuthoritySettings {
  @SerializedName("id")
  private String id = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("issuerDn")
  private String issuerDn = null;

  @SerializedName("mapsToCaConnectionName")
  private String mapsToCaConnectionName = null;

  @SerializedName("baseUrl")
  private String baseUrl = null;

  @SerializedName("additionalSettings")
  private List<AdditionalSetting> additionalSettings = null;

  public CertificateAuthoritySettings id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CertificateAuthoritySettings type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public CertificateAuthoritySettings name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CertificateAuthoritySettings issuerDn(String issuerDn) {
    this.issuerDn = issuerDn;
    return this;
  }

   /**
   * Get issuerDn
   * @return issuerDn
  **/
  @Schema(description = "")
  public String getIssuerDn() {
    return issuerDn;
  }

  public void setIssuerDn(String issuerDn) {
    this.issuerDn = issuerDn;
  }

  public CertificateAuthoritySettings mapsToCaConnectionName(String mapsToCaConnectionName) {
    this.mapsToCaConnectionName = mapsToCaConnectionName;
    return this;
  }

   /**
   * Get mapsToCaConnectionName
   * @return mapsToCaConnectionName
  **/
  @Schema(description = "")
  public String getMapsToCaConnectionName() {
    return mapsToCaConnectionName;
  }

  public void setMapsToCaConnectionName(String mapsToCaConnectionName) {
    this.mapsToCaConnectionName = mapsToCaConnectionName;
  }

  public CertificateAuthoritySettings baseUrl(String baseUrl) {
    this.baseUrl = baseUrl;
    return this;
  }

   /**
   * Get baseUrl
   * @return baseUrl
  **/
  @Schema(description = "")
  public String getBaseUrl() {
    return baseUrl;
  }

  public void setBaseUrl(String baseUrl) {
    this.baseUrl = baseUrl;
  }

  public CertificateAuthoritySettings additionalSettings(List<AdditionalSetting> additionalSettings) {
    this.additionalSettings = additionalSettings;
    return this;
  }

  public CertificateAuthoritySettings addAdditionalSettingsItem(AdditionalSetting additionalSettingsItem) {
    if (this.additionalSettings == null) {
      this.additionalSettings = new ArrayList<AdditionalSetting>();
    }
    this.additionalSettings.add(additionalSettingsItem);
    return this;
  }

   /**
   * Get additionalSettings
   * @return additionalSettings
  **/
  @Schema(description = "")
  public List<AdditionalSetting> getAdditionalSettings() {
    return additionalSettings;
  }

  public void setAdditionalSettings(List<AdditionalSetting> additionalSettings) {
    this.additionalSettings = additionalSettings;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificateAuthoritySettings certificateAuthoritySettings = (CertificateAuthoritySettings) o;
    return Objects.equals(this.id, certificateAuthoritySettings.id) &&
        Objects.equals(this.type, certificateAuthoritySettings.type) &&
        Objects.equals(this.name, certificateAuthoritySettings.name) &&
        Objects.equals(this.issuerDn, certificateAuthoritySettings.issuerDn) &&
        Objects.equals(this.mapsToCaConnectionName, certificateAuthoritySettings.mapsToCaConnectionName) &&
        Objects.equals(this.baseUrl, certificateAuthoritySettings.baseUrl) &&
        Objects.equals(this.additionalSettings, certificateAuthoritySettings.additionalSettings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, name, issuerDn, mapsToCaConnectionName, baseUrl, additionalSettings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificateAuthoritySettings {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    issuerDn: ").append(toIndentedString(issuerDn)).append("\n");
    sb.append("    mapsToCaConnectionName: ").append(toIndentedString(mapsToCaConnectionName)).append("\n");
    sb.append("    baseUrl: ").append(toIndentedString(baseUrl)).append("\n");
    sb.append("    additionalSettings: ").append(toIndentedString(additionalSettings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
