/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.winllc.acme.common.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * DailyAuditMetric
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-12T15:21:01.254Z[GMT]")
public class DailyAuditMetric {
  @SerializedName("date")
  private String date = null;

  @SerializedName("recordsTotal")
  private Integer recordsTotal = null;

  @SerializedName("auditRecords")
  private List<AuditRecord> auditRecords = null;

  public DailyAuditMetric date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @Schema(description = "")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public DailyAuditMetric recordsTotal(Integer recordsTotal) {
    this.recordsTotal = recordsTotal;
    return this;
  }

   /**
   * Get recordsTotal
   * @return recordsTotal
  **/
  @Schema(description = "")
  public Integer getRecordsTotal() {
    return recordsTotal;
  }

  public void setRecordsTotal(Integer recordsTotal) {
    this.recordsTotal = recordsTotal;
  }

  public DailyAuditMetric auditRecords(List<AuditRecord> auditRecords) {
    this.auditRecords = auditRecords;
    return this;
  }

  public DailyAuditMetric addAuditRecordsItem(AuditRecord auditRecordsItem) {
    if (this.auditRecords == null) {
      this.auditRecords = new ArrayList<AuditRecord>();
    }
    this.auditRecords.add(auditRecordsItem);
    return this;
  }

   /**
   * Get auditRecords
   * @return auditRecords
  **/
  @Schema(description = "")
  public List<AuditRecord> getAuditRecords() {
    return auditRecords;
  }

  public void setAuditRecords(List<AuditRecord> auditRecords) {
    this.auditRecords = auditRecords;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DailyAuditMetric dailyAuditMetric = (DailyAuditMetric) o;
    return Objects.equals(this.date, dailyAuditMetric.date) &&
        Objects.equals(this.recordsTotal, dailyAuditMetric.recordsTotal) &&
        Objects.equals(this.auditRecords, dailyAuditMetric.auditRecords);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, recordsTotal, auditRecords);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DailyAuditMetric {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    recordsTotal: ").append(toIndentedString(recordsTotal)).append("\n");
    sb.append("    auditRecords: ").append(toIndentedString(auditRecords)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
