/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.winllc.acme.common.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * DomainPolicyForm
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-12T15:21:01.254Z[GMT]")
public class DomainPolicyForm {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("objectUuid")
  private String objectUuid = null;

  @SerializedName("objectClass")
  private String objectClass = null;

  @SerializedName("errors")
  private Map<String, String> errors = null;

  @SerializedName("domainId")
  private Long domainId = null;

  @SerializedName("domainName")
  private String domainName = null;

  @SerializedName("allowIssuance")
  private Boolean allowIssuance = null;

  @SerializedName("acmeRequireHttpValidation")
  private Boolean acmeRequireHttpValidation = null;

  @SerializedName("acmeRequireDnsValidation")
  private Boolean acmeRequireDnsValidation = null;

  @SerializedName("subDomainForms")
  private List<DomainPolicyForm> subDomainForms = null;

  @SerializedName("valid")
  private Boolean valid = null;

  @SerializedName("accountLinkedForm")
  private Boolean accountLinkedForm = null;

  @SerializedName("uniqueEntityForm")
  private Boolean uniqueEntityForm = null;

  public DomainPolicyForm id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public DomainPolicyForm objectUuid(String objectUuid) {
    this.objectUuid = objectUuid;
    return this;
  }

   /**
   * Get objectUuid
   * @return objectUuid
  **/
  @Schema(description = "")
  public String getObjectUuid() {
    return objectUuid;
  }

  public void setObjectUuid(String objectUuid) {
    this.objectUuid = objectUuid;
  }

  public DomainPolicyForm objectClass(String objectClass) {
    this.objectClass = objectClass;
    return this;
  }

   /**
   * Get objectClass
   * @return objectClass
  **/
  @Schema(description = "")
  public String getObjectClass() {
    return objectClass;
  }

  public void setObjectClass(String objectClass) {
    this.objectClass = objectClass;
  }

  public DomainPolicyForm errors(Map<String, String> errors) {
    this.errors = errors;
    return this;
  }

  public DomainPolicyForm putErrorsItem(String key, String errorsItem) {
    if (this.errors == null) {
      this.errors = new HashMap<String, String>();
    }
    this.errors.put(key, errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @Schema(description = "")
  public Map<String, String> getErrors() {
    return errors;
  }

  public void setErrors(Map<String, String> errors) {
    this.errors = errors;
  }

  public DomainPolicyForm domainId(Long domainId) {
    this.domainId = domainId;
    return this;
  }

   /**
   * Get domainId
   * @return domainId
  **/
  @Schema(description = "")
  public Long getDomainId() {
    return domainId;
  }

  public void setDomainId(Long domainId) {
    this.domainId = domainId;
  }

  public DomainPolicyForm domainName(String domainName) {
    this.domainName = domainName;
    return this;
  }

   /**
   * Get domainName
   * @return domainName
  **/
  @Schema(description = "")
  public String getDomainName() {
    return domainName;
  }

  public void setDomainName(String domainName) {
    this.domainName = domainName;
  }

  public DomainPolicyForm allowIssuance(Boolean allowIssuance) {
    this.allowIssuance = allowIssuance;
    return this;
  }

   /**
   * Get allowIssuance
   * @return allowIssuance
  **/
  @Schema(description = "")
  public Boolean isAllowIssuance() {
    return allowIssuance;
  }

  public void setAllowIssuance(Boolean allowIssuance) {
    this.allowIssuance = allowIssuance;
  }

  public DomainPolicyForm acmeRequireHttpValidation(Boolean acmeRequireHttpValidation) {
    this.acmeRequireHttpValidation = acmeRequireHttpValidation;
    return this;
  }

   /**
   * Get acmeRequireHttpValidation
   * @return acmeRequireHttpValidation
  **/
  @Schema(description = "")
  public Boolean isAcmeRequireHttpValidation() {
    return acmeRequireHttpValidation;
  }

  public void setAcmeRequireHttpValidation(Boolean acmeRequireHttpValidation) {
    this.acmeRequireHttpValidation = acmeRequireHttpValidation;
  }

  public DomainPolicyForm acmeRequireDnsValidation(Boolean acmeRequireDnsValidation) {
    this.acmeRequireDnsValidation = acmeRequireDnsValidation;
    return this;
  }

   /**
   * Get acmeRequireDnsValidation
   * @return acmeRequireDnsValidation
  **/
  @Schema(description = "")
  public Boolean isAcmeRequireDnsValidation() {
    return acmeRequireDnsValidation;
  }

  public void setAcmeRequireDnsValidation(Boolean acmeRequireDnsValidation) {
    this.acmeRequireDnsValidation = acmeRequireDnsValidation;
  }

  public DomainPolicyForm subDomainForms(List<DomainPolicyForm> subDomainForms) {
    this.subDomainForms = subDomainForms;
    return this;
  }

  public DomainPolicyForm addSubDomainFormsItem(DomainPolicyForm subDomainFormsItem) {
    if (this.subDomainForms == null) {
      this.subDomainForms = new ArrayList<DomainPolicyForm>();
    }
    this.subDomainForms.add(subDomainFormsItem);
    return this;
  }

   /**
   * Get subDomainForms
   * @return subDomainForms
  **/
  @Schema(description = "")
  public List<DomainPolicyForm> getSubDomainForms() {
    return subDomainForms;
  }

  public void setSubDomainForms(List<DomainPolicyForm> subDomainForms) {
    this.subDomainForms = subDomainForms;
  }

  public DomainPolicyForm valid(Boolean valid) {
    this.valid = valid;
    return this;
  }

   /**
   * Get valid
   * @return valid
  **/
  @Schema(description = "")
  public Boolean isValid() {
    return valid;
  }

  public void setValid(Boolean valid) {
    this.valid = valid;
  }

  public DomainPolicyForm accountLinkedForm(Boolean accountLinkedForm) {
    this.accountLinkedForm = accountLinkedForm;
    return this;
  }

   /**
   * Get accountLinkedForm
   * @return accountLinkedForm
  **/
  @Schema(description = "")
  public Boolean isAccountLinkedForm() {
    return accountLinkedForm;
  }

  public void setAccountLinkedForm(Boolean accountLinkedForm) {
    this.accountLinkedForm = accountLinkedForm;
  }

  public DomainPolicyForm uniqueEntityForm(Boolean uniqueEntityForm) {
    this.uniqueEntityForm = uniqueEntityForm;
    return this;
  }

   /**
   * Get uniqueEntityForm
   * @return uniqueEntityForm
  **/
  @Schema(description = "")
  public Boolean isUniqueEntityForm() {
    return uniqueEntityForm;
  }

  public void setUniqueEntityForm(Boolean uniqueEntityForm) {
    this.uniqueEntityForm = uniqueEntityForm;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DomainPolicyForm domainPolicyForm = (DomainPolicyForm) o;
    return Objects.equals(this.id, domainPolicyForm.id) &&
        Objects.equals(this.objectUuid, domainPolicyForm.objectUuid) &&
        Objects.equals(this.objectClass, domainPolicyForm.objectClass) &&
        Objects.equals(this.errors, domainPolicyForm.errors) &&
        Objects.equals(this.domainId, domainPolicyForm.domainId) &&
        Objects.equals(this.domainName, domainPolicyForm.domainName) &&
        Objects.equals(this.allowIssuance, domainPolicyForm.allowIssuance) &&
        Objects.equals(this.acmeRequireHttpValidation, domainPolicyForm.acmeRequireHttpValidation) &&
        Objects.equals(this.acmeRequireDnsValidation, domainPolicyForm.acmeRequireDnsValidation) &&
        Objects.equals(this.subDomainForms, domainPolicyForm.subDomainForms) &&
        Objects.equals(this.valid, domainPolicyForm.valid) &&
        Objects.equals(this.accountLinkedForm, domainPolicyForm.accountLinkedForm) &&
        Objects.equals(this.uniqueEntityForm, domainPolicyForm.uniqueEntityForm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, objectUuid, objectClass, errors, domainId, domainName, allowIssuance, acmeRequireHttpValidation, acmeRequireDnsValidation, subDomainForms, valid, accountLinkedForm, uniqueEntityForm);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DomainPolicyForm {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    objectUuid: ").append(toIndentedString(objectUuid)).append("\n");
    sb.append("    objectClass: ").append(toIndentedString(objectClass)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    domainId: ").append(toIndentedString(domainId)).append("\n");
    sb.append("    domainName: ").append(toIndentedString(domainName)).append("\n");
    sb.append("    allowIssuance: ").append(toIndentedString(allowIssuance)).append("\n");
    sb.append("    acmeRequireHttpValidation: ").append(toIndentedString(acmeRequireHttpValidation)).append("\n");
    sb.append("    acmeRequireDnsValidation: ").append(toIndentedString(acmeRequireDnsValidation)).append("\n");
    sb.append("    subDomainForms: ").append(toIndentedString(subDomainForms)).append("\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("    accountLinkedForm: ").append(toIndentedString(accountLinkedForm)).append("\n");
    sb.append("    uniqueEntityForm: ").append(toIndentedString(uniqueEntityForm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
