/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.winllc.acme.common.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.HashMap;
import java.util.Map;
/**
 * ExternalAccountProviderSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-12T15:21:01.254Z[GMT]")
public class ExternalAccountProviderSettings {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("baseUrl")
  private String baseUrl = null;

  @SerializedName("accountVerificationUrl")
  private String accountVerificationUrl = null;

  @SerializedName("accountValidationRulesUrl")
  private String accountValidationRulesUrl = null;

  @SerializedName("additionalSettings")
  private Map<String, String> additionalSettings = null;

  public ExternalAccountProviderSettings id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ExternalAccountProviderSettings name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ExternalAccountProviderSettings baseUrl(String baseUrl) {
    this.baseUrl = baseUrl;
    return this;
  }

   /**
   * Get baseUrl
   * @return baseUrl
  **/
  @Schema(description = "")
  public String getBaseUrl() {
    return baseUrl;
  }

  public void setBaseUrl(String baseUrl) {
    this.baseUrl = baseUrl;
  }

  public ExternalAccountProviderSettings accountVerificationUrl(String accountVerificationUrl) {
    this.accountVerificationUrl = accountVerificationUrl;
    return this;
  }

   /**
   * Get accountVerificationUrl
   * @return accountVerificationUrl
  **/
  @Schema(description = "")
  public String getAccountVerificationUrl() {
    return accountVerificationUrl;
  }

  public void setAccountVerificationUrl(String accountVerificationUrl) {
    this.accountVerificationUrl = accountVerificationUrl;
  }

  public ExternalAccountProviderSettings accountValidationRulesUrl(String accountValidationRulesUrl) {
    this.accountValidationRulesUrl = accountValidationRulesUrl;
    return this;
  }

   /**
   * Get accountValidationRulesUrl
   * @return accountValidationRulesUrl
  **/
  @Schema(description = "")
  public String getAccountValidationRulesUrl() {
    return accountValidationRulesUrl;
  }

  public void setAccountValidationRulesUrl(String accountValidationRulesUrl) {
    this.accountValidationRulesUrl = accountValidationRulesUrl;
  }

  public ExternalAccountProviderSettings additionalSettings(Map<String, String> additionalSettings) {
    this.additionalSettings = additionalSettings;
    return this;
  }

  public ExternalAccountProviderSettings putAdditionalSettingsItem(String key, String additionalSettingsItem) {
    if (this.additionalSettings == null) {
      this.additionalSettings = new HashMap<String, String>();
    }
    this.additionalSettings.put(key, additionalSettingsItem);
    return this;
  }

   /**
   * Get additionalSettings
   * @return additionalSettings
  **/
  @Schema(description = "")
  public Map<String, String> getAdditionalSettings() {
    return additionalSettings;
  }

  public void setAdditionalSettings(Map<String, String> additionalSettings) {
    this.additionalSettings = additionalSettings;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalAccountProviderSettings externalAccountProviderSettings = (ExternalAccountProviderSettings) o;
    return Objects.equals(this.id, externalAccountProviderSettings.id) &&
        Objects.equals(this.name, externalAccountProviderSettings.name) &&
        Objects.equals(this.baseUrl, externalAccountProviderSettings.baseUrl) &&
        Objects.equals(this.accountVerificationUrl, externalAccountProviderSettings.accountVerificationUrl) &&
        Objects.equals(this.accountValidationRulesUrl, externalAccountProviderSettings.accountValidationRulesUrl) &&
        Objects.equals(this.additionalSettings, externalAccountProviderSettings.additionalSettings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, baseUrl, accountVerificationUrl, accountValidationRulesUrl, additionalSettings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalAccountProviderSettings {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    baseUrl: ").append(toIndentedString(baseUrl)).append("\n");
    sb.append("    accountVerificationUrl: ").append(toIndentedString(accountVerificationUrl)).append("\n");
    sb.append("    accountValidationRulesUrl: ").append(toIndentedString(accountValidationRulesUrl)).append("\n");
    sb.append("    additionalSettings: ").append(toIndentedString(additionalSettings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
