/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.winllc.acme.common.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * RACertificateIssueRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-12T15:21:01.254Z[GMT]")
public class RACertificateIssueRequest {
  @SerializedName("certAuthorityName")
  private String certAuthorityName = null;

  @SerializedName("existingCertificateRequestId")
  private Long existingCertificateRequestId = null;

  @SerializedName("accountKid")
  private String accountKid = null;

  @SerializedName("subjectNameRequest")
  private String subjectNameRequest = null;

  @SerializedName("csr")
  private String csr = null;

  @SerializedName("dnsNames")
  private String dnsNames = null;

  @SerializedName("source")
  private String source = null;

  public RACertificateIssueRequest certAuthorityName(String certAuthorityName) {
    this.certAuthorityName = certAuthorityName;
    return this;
  }

   /**
   * Get certAuthorityName
   * @return certAuthorityName
  **/
  @Schema(description = "")
  public String getCertAuthorityName() {
    return certAuthorityName;
  }

  public void setCertAuthorityName(String certAuthorityName) {
    this.certAuthorityName = certAuthorityName;
  }

  public RACertificateIssueRequest existingCertificateRequestId(Long existingCertificateRequestId) {
    this.existingCertificateRequestId = existingCertificateRequestId;
    return this;
  }

   /**
   * Get existingCertificateRequestId
   * @return existingCertificateRequestId
  **/
  @Schema(description = "")
  public Long getExistingCertificateRequestId() {
    return existingCertificateRequestId;
  }

  public void setExistingCertificateRequestId(Long existingCertificateRequestId) {
    this.existingCertificateRequestId = existingCertificateRequestId;
  }

  public RACertificateIssueRequest accountKid(String accountKid) {
    this.accountKid = accountKid;
    return this;
  }

   /**
   * Get accountKid
   * @return accountKid
  **/
  @Schema(description = "")
  public String getAccountKid() {
    return accountKid;
  }

  public void setAccountKid(String accountKid) {
    this.accountKid = accountKid;
  }

  public RACertificateIssueRequest subjectNameRequest(String subjectNameRequest) {
    this.subjectNameRequest = subjectNameRequest;
    return this;
  }

   /**
   * Get subjectNameRequest
   * @return subjectNameRequest
  **/
  @Schema(description = "")
  public String getSubjectNameRequest() {
    return subjectNameRequest;
  }

  public void setSubjectNameRequest(String subjectNameRequest) {
    this.subjectNameRequest = subjectNameRequest;
  }

  public RACertificateIssueRequest csr(String csr) {
    this.csr = csr;
    return this;
  }

   /**
   * Get csr
   * @return csr
  **/
  @Schema(description = "")
  public String getCsr() {
    return csr;
  }

  public void setCsr(String csr) {
    this.csr = csr;
  }

  public RACertificateIssueRequest dnsNames(String dnsNames) {
    this.dnsNames = dnsNames;
    return this;
  }

   /**
   * Get dnsNames
   * @return dnsNames
  **/
  @Schema(description = "")
  public String getDnsNames() {
    return dnsNames;
  }

  public void setDnsNames(String dnsNames) {
    this.dnsNames = dnsNames;
  }

  public RACertificateIssueRequest source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @Schema(description = "")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RACertificateIssueRequest raCertificateIssueRequest = (RACertificateIssueRequest) o;
    return Objects.equals(this.certAuthorityName, raCertificateIssueRequest.certAuthorityName) &&
        Objects.equals(this.existingCertificateRequestId, raCertificateIssueRequest.existingCertificateRequestId) &&
        Objects.equals(this.accountKid, raCertificateIssueRequest.accountKid) &&
        Objects.equals(this.subjectNameRequest, raCertificateIssueRequest.subjectNameRequest) &&
        Objects.equals(this.csr, raCertificateIssueRequest.csr) &&
        Objects.equals(this.dnsNames, raCertificateIssueRequest.dnsNames) &&
        Objects.equals(this.source, raCertificateIssueRequest.source);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certAuthorityName, existingCertificateRequestId, accountKid, subjectNameRequest, csr, dnsNames, source);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RACertificateIssueRequest {\n");
    
    sb.append("    certAuthorityName: ").append(toIndentedString(certAuthorityName)).append("\n");
    sb.append("    existingCertificateRequestId: ").append(toIndentedString(existingCertificateRequestId)).append("\n");
    sb.append("    accountKid: ").append(toIndentedString(accountKid)).append("\n");
    sb.append("    subjectNameRequest: ").append(toIndentedString(subjectNameRequest)).append("\n");
    sb.append("    csr: ").append(toIndentedString(csr)).append("\n");
    sb.append("    dnsNames: ").append(toIndentedString(dnsNames)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
