/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.winllc.acme.common.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * ServerSettingsGroup
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-12T15:21:01.254Z[GMT]")
public class ServerSettingsGroup {
  @SerializedName("settingsGroupName")
  private String settingsGroupName = null;

  @SerializedName("requiredSettings")
  private List<ServerSettings> requiredSettings = null;

  public ServerSettingsGroup settingsGroupName(String settingsGroupName) {
    this.settingsGroupName = settingsGroupName;
    return this;
  }

   /**
   * Get settingsGroupName
   * @return settingsGroupName
  **/
  @Schema(description = "")
  public String getSettingsGroupName() {
    return settingsGroupName;
  }

  public void setSettingsGroupName(String settingsGroupName) {
    this.settingsGroupName = settingsGroupName;
  }

  public ServerSettingsGroup requiredSettings(List<ServerSettings> requiredSettings) {
    this.requiredSettings = requiredSettings;
    return this;
  }

  public ServerSettingsGroup addRequiredSettingsItem(ServerSettings requiredSettingsItem) {
    if (this.requiredSettings == null) {
      this.requiredSettings = new ArrayList<ServerSettings>();
    }
    this.requiredSettings.add(requiredSettingsItem);
    return this;
  }

   /**
   * Get requiredSettings
   * @return requiredSettings
  **/
  @Schema(description = "")
  public List<ServerSettings> getRequiredSettings() {
    return requiredSettings;
  }

  public void setRequiredSettings(List<ServerSettings> requiredSettings) {
    this.requiredSettings = requiredSettings;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerSettingsGroup serverSettingsGroup = (ServerSettingsGroup) o;
    return Objects.equals(this.settingsGroupName, serverSettingsGroup.settingsGroupName) &&
        Objects.equals(this.requiredSettings, serverSettingsGroup.requiredSettings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(settingsGroupName, requiredSettings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerSettingsGroup {\n");
    
    sb.append("    settingsGroupName: ").append(toIndentedString(settingsGroupName)).append("\n");
    sb.append("    requiredSettings: ").append(toIndentedString(requiredSettings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
