/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.winllc.acme.common.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.UUID;
/**
 * ServerEntry
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-12T15:21:01.254Z[GMT]")
public class ServerEntry {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("uuid")
  private UUID uuid = null;

  @SerializedName("dn")
  private ServerEntryDn dn = null;

  @SerializedName("hostname")
  private String hostname = null;

  @SerializedName("fqdn")
  private String fqdn = null;

  @SerializedName("distinguishedName")
  private String distinguishedName = null;

  @SerializedName("openidClientId")
  private String openidClientId = null;

  @SerializedName("openidClientRedirectUrl")
  private String openidClientRedirectUrl = null;

  @SerializedName("acmeAllowPreAuthz")
  private Boolean acmeAllowPreAuthz = null;

  @SerializedName("new")
  private Boolean _new = null;

  public ServerEntry id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ServerEntry uuid(UUID uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @Schema(description = "")
  public UUID getUuid() {
    return uuid;
  }

  public void setUuid(UUID uuid) {
    this.uuid = uuid;
  }

  public ServerEntry dn(ServerEntryDn dn) {
    this.dn = dn;
    return this;
  }

   /**
   * Get dn
   * @return dn
  **/
  @Schema(description = "")
  public ServerEntryDn getDn() {
    return dn;
  }

  public void setDn(ServerEntryDn dn) {
    this.dn = dn;
  }

  public ServerEntry hostname(String hostname) {
    this.hostname = hostname;
    return this;
  }

   /**
   * Get hostname
   * @return hostname
  **/
  @Schema(description = "")
  public String getHostname() {
    return hostname;
  }

  public void setHostname(String hostname) {
    this.hostname = hostname;
  }

  public ServerEntry fqdn(String fqdn) {
    this.fqdn = fqdn;
    return this;
  }

   /**
   * Get fqdn
   * @return fqdn
  **/
  @Schema(description = "")
  public String getFqdn() {
    return fqdn;
  }

  public void setFqdn(String fqdn) {
    this.fqdn = fqdn;
  }

  public ServerEntry distinguishedName(String distinguishedName) {
    this.distinguishedName = distinguishedName;
    return this;
  }

   /**
   * Get distinguishedName
   * @return distinguishedName
  **/
  @Schema(description = "")
  public String getDistinguishedName() {
    return distinguishedName;
  }

  public void setDistinguishedName(String distinguishedName) {
    this.distinguishedName = distinguishedName;
  }

  public ServerEntry openidClientId(String openidClientId) {
    this.openidClientId = openidClientId;
    return this;
  }

   /**
   * Get openidClientId
   * @return openidClientId
  **/
  @Schema(description = "")
  public String getOpenidClientId() {
    return openidClientId;
  }

  public void setOpenidClientId(String openidClientId) {
    this.openidClientId = openidClientId;
  }

  public ServerEntry openidClientRedirectUrl(String openidClientRedirectUrl) {
    this.openidClientRedirectUrl = openidClientRedirectUrl;
    return this;
  }

   /**
   * Get openidClientRedirectUrl
   * @return openidClientRedirectUrl
  **/
  @Schema(description = "")
  public String getOpenidClientRedirectUrl() {
    return openidClientRedirectUrl;
  }

  public void setOpenidClientRedirectUrl(String openidClientRedirectUrl) {
    this.openidClientRedirectUrl = openidClientRedirectUrl;
  }

  public ServerEntry acmeAllowPreAuthz(Boolean acmeAllowPreAuthz) {
    this.acmeAllowPreAuthz = acmeAllowPreAuthz;
    return this;
  }

   /**
   * Get acmeAllowPreAuthz
   * @return acmeAllowPreAuthz
  **/
  @Schema(description = "")
  public Boolean isAcmeAllowPreAuthz() {
    return acmeAllowPreAuthz;
  }

  public void setAcmeAllowPreAuthz(Boolean acmeAllowPreAuthz) {
    this.acmeAllowPreAuthz = acmeAllowPreAuthz;
  }

  public ServerEntry _new(Boolean _new) {
    this._new = _new;
    return this;
  }

   /**
   * Get _new
   * @return _new
  **/
  @Schema(description = "")
  public Boolean isNew() {
    return _new;
  }

  public void setNew(Boolean _new) {
    this._new = _new;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerEntry serverEntry = (ServerEntry) o;
    return Objects.equals(this.id, serverEntry.id) &&
        Objects.equals(this.uuid, serverEntry.uuid) &&
        Objects.equals(this.dn, serverEntry.dn) &&
        Objects.equals(this.hostname, serverEntry.hostname) &&
        Objects.equals(this.fqdn, serverEntry.fqdn) &&
        Objects.equals(this.distinguishedName, serverEntry.distinguishedName) &&
        Objects.equals(this.openidClientId, serverEntry.openidClientId) &&
        Objects.equals(this.openidClientRedirectUrl, serverEntry.openidClientRedirectUrl) &&
        Objects.equals(this.acmeAllowPreAuthz, serverEntry.acmeAllowPreAuthz) &&
        Objects.equals(this._new, serverEntry._new);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, uuid, dn, hostname, fqdn, distinguishedName, openidClientId, openidClientRedirectUrl, acmeAllowPreAuthz, _new);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerEntry {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    dn: ").append(toIndentedString(dn)).append("\n");
    sb.append("    hostname: ").append(toIndentedString(hostname)).append("\n");
    sb.append("    fqdn: ").append(toIndentedString(fqdn)).append("\n");
    sb.append("    distinguishedName: ").append(toIndentedString(distinguishedName)).append("\n");
    sb.append("    openidClientId: ").append(toIndentedString(openidClientId)).append("\n");
    sb.append("    openidClientRedirectUrl: ").append(toIndentedString(openidClientRedirectUrl)).append("\n");
    sb.append("    acmeAllowPreAuthz: ").append(toIndentedString(acmeAllowPreAuthz)).append("\n");
    sb.append("    _new: ").append(toIndentedString(_new)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
